project:
  type: website
  output-dir: docs

website:
  title: "Resources for Students"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mediationsanalyse.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



